[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Gradle Plugins
paperweight = "2.0.0-beta.16"
shadow = "9.0.0-beta12"
runPaper = "2.3.1"

# Minecraft API
## Paper API
paper = "1.21.5-R0.1-SNAPSHOT"
minecraft = "1.21.5"
brigadier = "1.3.10"

[libraries]
# Minecraft API
## Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

## Mojang API
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }